### ISSUE TITLE
End of life?

### ISSUE THREAD

**Issue by gonggqing** [simeonradivoev/gameflow-launcher#1]
Will this app be updated again ? Need help on how to install it, thanks. Favour the UI style.

**Comment by simeonradivoev** [comment]
yea I kinda gave up on it

**Comment by gonggqing** [comment]
Thanks for your reply! Currently, I am working on a project of automated game testing, which used Python to automate game benchmarks, and I think this project is a great front-end UI to integrate with my scripts! It would be very appreciated if you could give me simple instructions on how to install this project locally since I am new to typescript/javascript. But if you are busy working on other stuff, I would try on my own (I could try to use chatGPT to analyze this repo). Thanks for building this app anyway!

**Comment by simeonradivoev** [comment]
you need NPM.
Then you just need to call the command `npm install` in the main directory.
Then you can do `npm run start` to start the app or `npm run build` to make a build or `npm run package` to make a production-ready package.

It's based on the [Electron React Boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) you can check some of the instructions there, they should be pretty much the same.

**Comment by gonggqing** [comment]
Thanks a lot! I will follow these instructions!
